title: Priyesh Jani
logo: /assets/headshot-circle.png
description: Transforming raw data into actionable insights for strategic business growth
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
